In [48]:
import numpy as np

In [49]:
# Diifrent methods of creating array 

l = [1,2,3,4,5,6]
ar = np.array(l)
print(ar)
print(type(ar))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [50]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [51]:
print(np.asanyarray(l))
np.asanyarray(l)

# both are same but output

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [52]:
# SEE CAREFULLY
c = ar  # that means you can now access array using both "c" and "ar",location of ar and d is same
print(c) # that not means you store the data of ar into c
print(ar) 

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [53]:
d = np.copy(ar) # create a copy ar , location of ar and d is diff
d

array([1, 2, 3, 4, 5, 6])

In [54]:
ar

array([1, 2, 3, 4, 5, 6])

In [55]:
d[0] = 100
ar[1] = 400

print(d)
print(ar)

[100   2   3   4   5   6]
[  1 400   3   4   5   6]


In [56]:
b = np.matrix(l)  # [[ means its two dimensional matrix where y = 0 & x = 1,2,3,4,5,6
b

matrix([[1, 2, 3, 4, 5, 6]])

In [57]:
## you can convert array into matrix but you cant matrix into array,becoz the array is subset of matrix

np.asanyarray(b)  

matrix([[1, 2, 3, 4, 5, 6]])

In [59]:
np.fromfunction(lambda i,j : i==j , (3,3)) 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [61]:
np.fromfunction( lambda i,j: i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])