In [6]:
# iterable
import numpy as np

iterable = (i*i for i in range(5))
iterable

<generator object <genexpr> at 0x000002512246B030>

In [7]:
# create array by iterating
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [11]:
# create array from string
np.fromstring( "123 345", sep=" ")

array([123., 345.])

In [12]:
np.fromstring( '4,5', sep= ",")

array([4., 5.])