In [ ]:
# Numpy - data types

In [1]:
import numpy as np

l = [2,3,4,5,6]
ar = np.array(l)

In [2]:
ar

array([2, 3, 4, 5, 6])

In [3]:
ar.ndim  # how many dimesion of array

1

In [4]:
ar2 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #([(1,2,3,4,5),(6,7,8,9,100]) its also work
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
ar2.ndim

2

In [6]:
ar.size # number of elements

5

In [7]:
ar2.size  

10

In [8]:
ar.shape

# one row consists 5 elements

(5,)

In [9]:
ar2.shape

# two rows 5 columns

(2, 5)

In [10]:
ar.dtype

dtype('int32')

In [11]:
ar2.dtype

dtype('int32')

In [12]:
l1 = [(1.02,2,3,4), (24,8,6,4)]
ar3 = np.asarray(l1)
ar3

# there is only one float value in above list ,but during creating array it coverts all values into float

array([[ 1.02,  2.  ,  3.  ,  4.  ],
       [24.  ,  8.  ,  6.  ,  4.  ]])

In [13]:
type(ar3)

numpy.ndarray

In [15]:
ar3.dtype

dtype('float64')