In [34]:
# all gives output in array

In [35]:
# range == arange for numpy
import numpy as np
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [36]:
list(np.arange(2.3,5.3,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998]

In [37]:
np.arange(2.3,5.6,3) 

array([2.3, 5.3])

In [38]:
# linespace 

np.linspace(1,5,10)  # like a make 10 equal pieces from 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [40]:
np.logspace(2,5 , 10, base = 2)  
# 2** = 4,
# 2**x = 5.039,
# 2**x = 6.349,

# 2**5 = 32

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [41]:

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.zeros((2,3,5))  # 2 arrays of 3 rows and 5 columns

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [47]:
ar = np.zeros((3,4,3,2))  # 4-4 ke 3 sets
ar

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [48]:
ar.ndim 

4

In [49]:
on = np.ones((2,3,3))

In [50]:
on + 5

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [51]:
on * 4

array([[[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]])

In [52]:
np.empty((3,6))

array([[4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.]])

In [53]:
'''np.empty() is faster than zeros and ones ,
zeros and ones used when an array initilized with default values
    '''

'np.empty() is faster than zeros and ones ,\nzeros and ones used when an array initilized with default values\n    '

In [54]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])