In [1]:
import numpy as np

arr = np.random.randn(3,4)
arr

array([[ 0.80199903,  1.0030517 ,  0.57370573,  0.73586797],
       [-0.71985062, -0.35143414,  1.12703731, -0.5764536 ],
       [-1.66566176, -0.78641434, -1.19556305,  0.07840386]])

In [2]:
import pandas as pd

In [3]:
pd.DataFrame(arr)

0         1         2         3
0  0.801999  1.003052  0.573706  0.735868
1 -0.719851 -0.351434  1.127037 -0.576454
2 -1.665662 -0.786414 -1.195563  0.078404

In [4]:
# save file 
pd.DataFrame(np.random.randint(1,110, (10,2))).to_csv("random_numpy.csv")

In [5]:
arr = np.random.rand(3,4)
arr

array([[0.48024215, 0.17092578, 0.12051142, 0.0278453 ],
       [0.14534258, 0.4541255 , 0.63132471, 0.18233818],
       [0.87292734, 0.84061534, 0.4739658 , 0.75756042]])

In [7]:
# reshape the array
arr.reshape(6,2) # arr has 3*4 = 12
                 # so reshape must be 12 = (6,2)

# arr.reshape(5,3) it gives error

array([[0.48024215, 0.17092578],
       [0.12051142, 0.0278453 ],
       [0.14534258, 0.4541255 ],
       [0.63132471, 0.18233818],
       [0.87292734, 0.84061534],
       [0.4739658 , 0.75756042]])

In [9]:
arr.reshape(6,-1654) # it works

array([[0.48024215, 0.17092578],
       [0.12051142, 0.0278453 ],
       [0.14534258, 0.4541255 ],
       [0.63132471, 0.18233818],
       [0.87292734, 0.84061534],
       [0.4739658 , 0.75756042]])

In [10]:
arr.reshape(4,-164)

array([[0.48024215, 0.17092578, 0.12051142],
       [0.0278453 , 0.14534258, 0.4541255 ],
       [0.63132471, 0.18233818, 0.87292734],
       [0.84061534, 0.4739658 , 0.75756042]])

In [11]:
arr1 = arr.reshape(6,-1654)

In [12]:
arr1

array([[0.48024215, 0.17092578],
       [0.12051142, 0.0278453 ],
       [0.14534258, 0.4541255 ],
       [0.63132471, 0.18233818],
       [0.87292734, 0.84061534],
       [0.4739658 , 0.75756042]])

In [13]:
arr1[1]

array([0.12051142, 0.0278453 ])

In [15]:
arr1[1][1]

0.027845302885175505

In [22]:
arr1[1,1]

0.027845302885175505

In [17]:
arr1[2:5,1]

array([0.4541255 , 0.18233818, 0.84061534])

In [19]:
arr1[2:6]

array([[0.14534258, 0.4541255 ],
       [0.63132471, 0.18233818],
       [0.87292734, 0.84061534],
       [0.4739658 , 0.75756042]])

In [21]:
arr1[2:,1]

array([0.4541255 , 0.18233818, 0.84061534, 0.75756042])

In [23]:
arr = np.random.randint(1,110 , (5,5,))
arr

array([[ 54,  10,  76,  41,  90],
       [ 31,  87,  71,  43,  66],
       [ 81,  63,  17,  46,  42],
       [ 83,  60, 102,  89,  90],
       [  8,  40, 107,  74, 105]])

In [24]:
arr[arr > 50]

array([ 54,  76,  90,  87,  71,  66,  81,  63,  83,  60, 102,  89,  90,
       107,  74, 105])

In [25]:
arr

array([[ 54,  10,  76,  41,  90],
       [ 31,  87,  71,  43,  66],
       [ 81,  63,  17,  46,  42],
       [ 83,  60, 102,  89,  90],
       [  8,  40, 107,  74, 105]])

In [26]:
# extract specific data

arr[2:4, [1,2]]  # data from 2-3rd row and 1-2 column

array([[ 63,  17],
       [ 60, 102]])

In [27]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [28]:
arr1

array([[1, 2, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [29]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [2, 2, 2]])

In [30]:
arr1+arr2

array([[3, 4, 4],
       [3, 3, 3],
       [4, 4, 3]])

In [33]:
arr1-arr2

array([[ 0,  0, -1],
       [ 0,  0, -1],
       [-1,  1,  0]])

In [32]:
arr1/arr2


array([[1. , 1. , 0.5],
       [1. , 1. , 0.5],
       [0.5, 2. , 1. ]])

In [34]:
arr1 * arr2 

array([[4, 1, 2],
       [4, 1, 2],
       [2, 2, 4]])

In [35]:
arr1@arr2  # proper matrix to matrix multiplication

array([[ 8,  4,  8],
       [ 8,  4,  8],
       [10,  5, 10]])

In [36]:
arr1/0

C:\Users\HP\AppData\Local\Temp\ipykernel_13432\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [37]:
arr1 +100

array([[102, 101, 101],
       [102, 101, 101],
       [101, 102, 102]])

In [38]:
arr1**2

array([[4, 1, 1],
       [4, 1, 1],
       [1, 4, 4]])