In [2]:
# Numpy - Broadcasting
import numpy as np

In [4]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
row = np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [6]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [9]:
row.T  # it doesnt transport becoz its 1 dimension
row.ndim #for conver row into column u need 2 dimension array

1

In [13]:
row = np.array([[1,2,3,4]])
row.ndim

2

In [17]:
row.T

array([[1],
       [2],
       [3],
       [4]])

In [14]:
arr + row.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [15]:
row

array([[1, 2, 3, 4]])

In [18]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
arr1 = np.random.randint( 1,4  , (3,4))
arr1

array([[2, 3, 1, 2],
       [3, 3, 2, 3],
       [2, 3, 2, 1]])

In [22]:
np.sqrt(arr1)

array([[1.41421356, 1.73205081, 1.        , 1.41421356],
       [1.73205081, 1.73205081, 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 1.41421356, 1.        ]])

In [23]:
np.log10(arr1)  # log10(x) = y
                # 10 ^ y = x 
                # 10 ^ 0.301 = 2

array([[0.30103   , 0.47712125, 0.        , 0.30103   ],
       [0.47712125, 0.47712125, 0.30103   , 0.47712125],
       [0.30103   , 0.47712125, 0.30103   , 0.        ]])

In [24]:
np.exp(arr1)  #exponintion


array([[ 7.3890561 , 20.08553692,  2.71828183,  7.3890561 ],
       [20.08553692, 20.08553692,  7.3890561 , 20.08553692],
       [ 7.3890561 , 20.08553692,  7.3890561 ,  2.71828183]])