In [32]:
# Numpy Array Manipulation

In [33]:
import numpy as np

arr = np.random.randint(1,10 , (3,4))
arr

array([[6, 2, 5, 6],
       [3, 5, 5, 8],
       [2, 4, 5, 1]])

In [34]:
arr.reshape(6,2)

array([[6, 2],
       [5, 6],
       [3, 5],
       [5, 8],
       [2, 4],
       [5, 1]])

In [35]:
arr.reshape(2,6)

array([[6, 2, 5, 6, 3, 5],
       [5, 8, 2, 4, 5, 1]])

In [36]:
arr.reshape(6,-51)

array([[6, 2],
       [5, 6],
       [3, 5],
       [5, 8],
       [2, 4],
       [5, 1]])

In [37]:
arr.flatten()

array([6, 2, 5, 6, 3, 5, 5, 8, 2, 4, 5, 1])

In [38]:
arr1 = np.array([1,2,3,4,5])
arr1.ndim

1

In [39]:
np.expand_dims(arr1,axis=0) ## see dim= 1 convert into dim= 2

array([[1, 2, 3, 4, 5]])

In [40]:
np.expand_dims(arr1,axis=1) # see dim= 1 convert into dim= 2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [41]:
arr

array([[6, 2, 5, 6],
       [3, 5, 5, 8],
       [2, 4, 5, 1]])

In [42]:
np.squeeze(arr)  # no any cahanges appear

array([[6, 2, 5, 6],
       [3, 5, 5, 8],
       [2, 4, 5, 1]])

In [43]:
array1 = np.array([[1],[2],[3],[4]])
print(array1)

data = np.squeeze(array1)  # cahnges appears becoz only one elements exists in each array
data

[[1]
 [2]
 [3]
 [4]]


array([1, 2, 3, 4])

In [44]:
array1

array([[1],
       [2],
       [3],
       [4]])

In [45]:
arr1

array([1, 2, 3, 4, 5])

In [46]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [47]:
np.roll(arr1,3)

array([3, 4, 5, 1, 2])

In [48]:
arr1

array([1, 2, 3, 4, 5])

In [49]:
np.diag(arr1)  # add array values in diagonal matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
#