In [1]:
# Numpy - Binary Opearrtions
import numpy as np

In [2]:
arr = np.random.randint(1,10 , (3,3))
arr

array([[4, 5, 8],
       [7, 7, 3],
       [9, 4, 2]])

In [3]:
arr1 = np.random.randint(1,10 , (3,3))
arr1

array([[9, 2, 1],
       [7, 4, 1],
       [6, 3, 1]])

In [4]:
arr + arr1

array([[13,  7,  9],
       [14, 11,  4],
       [15,  7,  3]])

In [5]:
arr + arr1

array([[13,  7,  9],
       [14, 11,  4],
       [15,  7,  3]])

In [6]:
arr & arr1

array([[0, 0, 0],
       [7, 4, 1],
       [0, 0, 0]])

In [7]:
arr 

array([[4, 5, 8],
       [7, 7, 3],
       [9, 4, 2]])

In [8]:
arr1

array([[9, 2, 1],
       [7, 4, 1],
       [6, 3, 1]])

In [9]:
arr | arr1

array([[13,  7,  9],
       [ 7,  7,  3],
       [15,  7,  3]])

In [10]:
arr / arr1

array([[0.44444444, 2.5       , 8.        ],
       [1.        , 1.75      , 3.        ],
       [1.5       , 1.33333333, 2.        ]])

In [11]:
arr%arr1

array([[4, 1, 0],
       [0, 3, 0],
       [3, 1, 0]])

In [12]:
arr>arr1

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
#Numpy - String Functions.

In [16]:
arr = np.array(['pratish' , "gurav"])

In [17]:
arr

array(['pratish', 'gurav'], dtype='<U7')

In [20]:
np.char.upper(arr)

array(['PRATISH', 'GURAV'], dtype='<U7')

In [21]:
np.char.title(arr)

array(['Pratish', 'Gurav'], dtype='<U7')

In [22]:
np.char.capitalize(arr)

array(['Pratish', 'Gurav'], dtype='<U7')

In [ ]:
#Numpy - Mathematical Functions.

In [23]:
arr1

array([[9, 2, 1],
       [7, 4, 1],
       [6, 3, 1]])

In [25]:
np.sin(arr1)

array([[ 0.41211849,  0.90929743,  0.84147098],
       [ 0.6569866 , -0.7568025 ,  0.84147098],
       [-0.2794155 ,  0.14112001,  0.84147098]])

In [27]:
np.tan(arr1)

array([[-0.45231566, -2.18503986,  1.55740772],
       [ 0.87144798,  1.15782128,  1.55740772],
       [-0.29100619, -0.14254654,  1.55740772]])

In [28]:
np.tanh(arr1)  #The np.tanh function in NumPy computes the hyperbolic tangent of each element in the array.

array([[0.99999997, 0.96402758, 0.76159416],
       [0.99999834, 0.9993293 , 0.76159416],
       [0.99998771, 0.99505475, 0.76159416]])

In [29]:
np.log10(arr1)

array([[0.95424251, 0.30103   , 0.        ],
       [0.84509804, 0.60205999, 0.        ],
       [0.77815125, 0.47712125, 0.        ]])

In [30]:
np.sqrt(arr1)

array([[3.        , 1.41421356, 1.        ],
       [2.64575131, 2.        , 1.        ],
       [2.44948974, 1.73205081, 1.        ]])

In [31]:
np.power(arr1,2)

array([[81,  4,  1],
       [49, 16,  1],
       [36,  9,  1]], dtype=int32)

In [32]:
np.mean(arr1)

3.7777777777777777

In [33]:
arr1.mean()

3.7777777777777777

In [34]:
np.std(arr1)

2.779999111821512

In [35]:
np.var(arr1)

7.728395061728396

In [36]:
arr1.var()

7.728395061728396

In [38]:
np.max(arr1)

9

In [39]:
arr1.max()

9