In [22]:
# sort ,search, and counting function
import numpy as np

In [23]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [24]:
arr.sort()

In [25]:
arr

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [26]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [27]:
np.searchsorted(arr,72)  # 72 located 10th position

10

In [28]:
np.searchsorted(arr,444)  # it tells where 444 will locate


11

In [29]:
arr1 = np.array([0,345,454,0,0,0,0,0])
arr1

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [30]:
np.count_nonzero(arr1)

2

In [31]:
arr

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [32]:
np.where(arr > 6)  # index of numbers that bigger than 6

(array([10, 11], dtype=int64),)

In [33]:
np.extract(arr > 6, arr)  # numbers that bigger than 6

array([ 72, 455])

In [34]:
#Numpy - Byte Swapping.

In [35]:
arr

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [36]:
arr.byteswap()

array([  50331648,   50331648,   50331648,   67108864,   67108864,
         83886080,   83886080,  100663296,  100663296,  100663296,
       1207959552, -956235776])

In [37]:
#Numpy - Copies &Views.

In [38]:
arr

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [39]:
a = np.copy(arr) # it create other copy of arr w
 
# cahnge make in "a" not affect on "arr"

In [40]:
b = arr # both arr and b is same both refers same array
# cahnges make in "a" is affect on "arr"

b = arr.view()  

In [41]:
b

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [42]:
arr

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [44]:
# numpy - Matrix Library

import numpy.matlib as nm

# it just give output in matrix format

In [45]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [46]:
nm.eye(5)


matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [47]:
# Numpy - Linear Algebra

In [48]:
arr1 = np.random.randint([[2,3], [4,5]])  # 2 dimension array

In [49]:
arr1

array([[1, 0],
       [2, 2]])

In [50]:
arr2 = np.random.randint([[5,3] , [2,5]])
arr2

array([[1, 2],
       [0, 3]])

In [52]:
np.dot(arr1,arr2)  # dot product

array([[ 1,  2],
       [ 2, 10]])

In [53]:
arr1@arr2   # multiplication

array([[ 1,  2],
       [ 2, 10]])