In [6]:
import numpy as np

# Define the array
arr = np.array([[9, 2, 1],
                [7, 4, 1],
                [6, 3, 1]])

# Create an iterator
it = np.nditer(arr, flags=['multi_index'], op_flags=['readwrite'])

# Iterate over the array
while not it.finished:
    if it[0] > 5:
        it[0] = it[0] - 5  # Example modification
    it.iternext()

print(arr)


[[4 2 1]
 [2 4 1]
 [1 3 1]]


In [2]:
import numpy as np

# Define the array
arr = np.array([[9, 2, 1],
                [7, 4, 1],
                [6, 3, 1]])

# Apply condition and modify elements
arr[arr > 5] -= 5  # Subtract 5 from elements greater than 5

print(arr)


[[4 2 1]
 [2 4 1]
 [1 3 1]]


In [3]:
import numpy as np

# Define the array
arr = np.array([[9, 2, 1],
                [7, 4, 1],
                [6, 3, 1]])

# Use np.where to apply condition and modify elements
arr = np.where(arr > 5, arr - 5, arr)

print(arr)


[[4 2 1]
 [2 4 1]
 [1 3 1]]
